use super::*;
use crate::register_leptos_routes;
use leptos::config::LeptosOptions;
use ntex::http::{StatusCode, header};
use ntex::web::{App as NtexApp, test};

#[ntex::test]
async fn static_route_generator_writes_html() {
    let site_root = temp_site_root("static");
    let (_routes, generator) = gen_route_list_with_ssg(StaticApp);
    let options = LeptosOptions::builder()
        .output_name("leptos_ntex_test")
        .site_root(site_root.to_string_lossy().to_string())
        .site_pkg_dir("pkg")
        .build();

    generator.generate(&options).await;

    let index_path = site_root.join("index.html");
    let about_path = site_root.join("about.html");

    let index_html = std::fs::read_to_string(&index_path).unwrap();
    let about_html = std::fs::read_to_string(&about_path).unwrap();

    assert!(index_html.contains("Static Home"));
    assert!(about_html.contains("Static About"));

    let _ = std::fs::remove_dir_all(&site_root);
}

/// HEAD on a statically pre-rendered route must mirror GET's status
/// and Content-Type. (Wire-level body elision is covered by the
/// TCP-based integration tests.)
#[ntex::test]
async fn head_request_on_static_route_mirrors_get() {
    let site_root = temp_site_root("head_static");
    let (routes, generator) = gen_route_list_with_ssg(StaticApp);
    let options = LeptosOptions::builder()
        .output_name("leptos_ntex_head_static")
        .site_root(site_root.to_string_lossy().to_string())
        .site_pkg_dir("pkg")
        .build();

    generator.generate(&options).await;

    let app = test::init_service(NtexApp::new().state(options.clone()).configure(|cfg| {
        register_leptos_routes(cfg, routes.clone(), StaticApp);
    }))
    .await;

    let get_resp = test::call_service(&app, test::TestRequest::with_uri("/").to_request()).await;
    assert_eq!(get_resp.status(), StatusCode::OK);
    let get_headers = get_resp.headers().clone();

    let head_resp = test::call_service(
        &app,
        test::TestRequest::default()
            .method(ntex::http::Method::HEAD)
            .uri("/")
            .to_request(),
    )
    .await;
    assert_eq!(head_resp.status(), StatusCode::OK);
    assert_eq!(
        head_resp.headers().get(header::CONTENT_TYPE),
        get_headers.get(header::CONTENT_TYPE)
    );

    let _ = std::fs::remove_dir_all(&site_root);
}

#[ntex::test]
async fn static_route_served_over_http() {
    let site_root = temp_site_root("http_static");
    let (routes, generator) = gen_route_list_with_ssg(StaticApp);
    let options = LeptosOptions::builder()
        .output_name("leptos_ntex_test_http")
        .site_root(site_root.to_string_lossy().to_string())
        .site_pkg_dir("pkg")
        .build();

    generator.generate(&options).await;

    let app = test::init_service(NtexApp::new().state(options.clone()).configure(|cfg| {
        register_leptos_routes(cfg, routes.clone(), StaticApp);
    }))
    .await;

    let req = test::TestRequest::with_uri("/").to_request();
    let resp = test::call_service(&app, req).await;
    assert_eq!(resp.status(), StatusCode::OK);

    let body = test::read_body(resp).await;
    let html = String::from_utf8(body.to_vec()).unwrap();
    assert!(html.contains("Static Home"));

    let _ = std::fs::remove_dir_all(&site_root);
}

/// On-demand regeneration of a `SsrMode::Static` route that was NOT
/// pre-generated by `StaticRouteGenerator::generate` must serve the freshly
/// rendered HTML, not a 500. `ResolvedStaticPath::build` writes the page to
/// disk and returns `None` on success (the body lives on disk, not in
/// memory), so the handler must re-read the just-written file — mirroring
/// leptos_axum (`ServeDir`) and leptos_actix (`NamedFile::open`). Regression
/// probe for the regeneration branch that the existing static-route tests
/// never exercise (they all call `generate()` first).
#[ntex::test]
async fn static_route_on_demand_regeneration_serves_html() {
    let site_root = temp_site_root("static_regen");
    std::fs::create_dir_all(&site_root).unwrap();
    let (routes, _generator) = gen_route_list_with_ssg(StaticApp);
    let options = LeptosOptions::builder()
        .output_name("leptos_ntex_test_regen")
        .site_root(site_root.to_string_lossy().to_string())
        .site_pkg_dir("pkg")
        .build();

    // Deliberately DO NOT call `_generator.generate(&options).await`: the
    // file is absent on disk, so the first request takes the on-demand
    // regeneration branch of `handle_static_route`.
    let app = test::init_service(NtexApp::new().state(options.clone()).configure(|cfg| {
        register_leptos_routes(cfg, routes.clone(), StaticApp);
    }))
    .await;

    let resp = test::call_service(&app, test::TestRequest::with_uri("/").to_request()).await;
    assert_eq!(
        resp.status(),
        StatusCode::OK,
        "first (regenerating) request to an un-pregenerated static route must serve 200, not 500"
    );
    let body = test::read_body(resp).await;
    let html = String::from_utf8(body.to_vec()).unwrap();
    assert!(
        html.contains("Static Home"),
        "must serve the rendered static HTML, got: {html}"
    );

    let _ = std::fs::remove_dir_all(&site_root);
}

/// Concurrent on-demand regenerations of the SAME static path must never
/// serve a body from one render under headers captured by another. Every
/// render of `StaticEpochApp` stamps a fresh epoch into both the body and
/// the `x-render-epoch` header; with the file initially absent, N parallel
/// first requests all race down the regeneration branch (the documented
/// stampede), each writing the file+header snapshot under the write stripe
/// and then re-opening the file. A re-open that pairs the on-disk body with
/// the REQUEST-LOCAL header snapshot (instead of reading both under the
/// stripe) lets a neighbour's freshly written body ship under this
/// request's older headers — the regression this pins down. The pairing
/// invariant must hold for every interleaving, so the test is
/// deterministic-green under the fix and only the broken pairing can flake
/// it red.
///
/// One-sided by nature: a red PROVES the pairing bug, while a green is
/// meaningful only while the stampede design lets renders overlap (no
/// barrier forces all 16 requests past the missing-file check before the
/// first write lands). Manual-Red evidence at introduction: against the
/// pre-fix unpaired re-open this failed 17/20 runs; with the fix, 10/10
/// green. If in-flight render dedup (single-flight) ever lands, only one
/// epoch will exist and this test stays trivially green — correctly so,
/// because the bug class is then designed away.
#[ntex::test]
async fn static_route_concurrent_regeneration_pairs_body_with_headers() {
    let site_root = temp_site_root("static_epoch_race");
    std::fs::create_dir_all(&site_root).unwrap();
    let (routes, _generator) = gen_route_list_with_ssg(StaticEpochApp);
    let options = LeptosOptions::builder()
        .output_name("leptos_ntex_static_epoch")
        .site_root(site_root.to_string_lossy().to_string())
        .site_pkg_dir("pkg")
        .build();

    // Deliberately no `generate()`: the file must be missing so the initial
    // requests take the regeneration branch concurrently.
    let app = test::init_service(NtexApp::new().state(options.clone()).configure(|cfg| {
        register_leptos_routes(cfg, routes.clone(), StaticEpochApp);
    }))
    .await;

    let responses = futures::future::join_all(
        (0..16)
            .map(|_| test::call_service(&app, test::TestRequest::with_uri("/epoch").to_request())),
    )
    .await;

    for resp in responses {
        assert_eq!(resp.status(), StatusCode::OK);
        let header_epoch = resp
            .headers()
            .get("x-render-epoch")
            .and_then(|v| v.to_str().ok())
            .map(str::to_string)
            .expect("every served static response must carry the captured header snapshot");
        let body = test::read_body(resp).await;
        let html = String::from_utf8(body.to_vec()).unwrap();
        let body_epoch = html
            .split("epoch-")
            .nth(1)
            .and_then(|tail| tail.split("-marker").next())
            .expect("rendered body must contain the epoch marker");
        assert_eq!(
            body_epoch, header_epoch,
            "body epoch and x-render-epoch header must come from one render"
        );
    }

    let _ = std::fs::remove_dir_all(&site_root);
}

#[ntex::test]
async fn static_route_cached_headers_are_replayed_more_than_once() {
    let site_root = temp_site_root("static_headers");
    let (routes, generator) = gen_route_list_with_ssg(StaticHeaderApp);
    let options = LeptosOptions::builder()
        .output_name("leptos_ntex_static_headers")
        .site_root(site_root.to_string_lossy().to_string())
        .site_pkg_dir("pkg")
        .build();

    generator.generate(&options).await;

    let app = test::init_service(NtexApp::new().state(options.clone()).configure(|cfg| {
        register_leptos_routes(cfg, routes.clone(), StaticHeaderApp);
    }))
    .await;

    for _ in 0..3 {
        let resp =
            test::call_service(&app, test::TestRequest::with_uri("/headers").to_request()).await;
        assert_eq!(resp.status(), StatusCode::CREATED);
        assert_eq!(
            resp.headers()
                .get("x-static-cache")
                .and_then(|v| v.to_str().ok()),
            Some("preserved")
        );
        let body = test::read_body(resp).await;
        let html = String::from_utf8(body.to_vec()).unwrap();
        assert!(html.contains("Static Headers"));
    }

    let _ = std::fs::remove_dir_all(&site_root);
}
