//! Live ISR: `cargo run --example isr_startup -- target/isr-site`
//! Visit http://127.0.0.1:3000/ and POST /refresh to update the public page.
//! Restart the same command: startup generation installs this process's listener.
//!
//! Read-only SSG: `cargo run --example isr_startup -- target/isr-site --prebuilt`
//! For existing complete artifacts, this skips startup generation and /refresh.
//! It does not disable the adapter's on-demand render for a missing/inconsistent
//! artifact. Enforce filesystem permissions separately for read-only deployment.
//! Add `--bounded` in live mode to demonstrate optional admission limits on Unix.
//! Its 1 MiB / 64 entries / 2 renders / 1 stream / 16 waiters are example values,
//! not library defaults. Reusing the root requires the same persisted limits.
//! The revision is demo data in memory, not a persistent application database.

use futures::channel::mpsc;
use leptos::prelude::*;
use leptos_meta::{MetaTags, provide_meta_context};
use leptos_ntex_unofficial::{
    ResponseOptions, StaticRoutePolicy, StaticStorageLimits, StaticWorkLimits,
    generate_route_list_with_exclusions_and_ssg_and_context, register_leptos_routes,
};
use leptos_router::{
    SsrMode,
    components::{Route, Router, Routes},
    path,
    static_routes::StaticRoute,
};
use ntex::{
    http::header,
    web::{self, App, HttpResponse, types::State},
};
use std::sync::{
    Arc, Mutex,
    atomic::{AtomicUsize, Ordering},
};

#[derive(Clone, Default)]
struct PublicPage {
    revision: Arc<AtomicUsize>,
    updates: Arc<Mutex<Option<mpsc::Sender<()>>>>,
}

impl PublicPage {
    fn subscribe(&self) -> mpsc::Receiver<()> {
        let (sender, receiver) = mpsc::channel(1);
        *self.updates.lock().expect("page updates lock") = Some(sender);
        receiver
    }
}

fn shell(page: PublicPage) -> impl IntoView {
    provide_meta_context();
    let subscribed = page.clone();
    view! {
        <!DOCTYPE html>
        <html lang="en"><head><title>"ISR startup"</title><MetaTags/></head><body>
            <Router><Routes fallback=|| "Not Found">
                <Route path=path!("/")
                    ssr=SsrMode::Static(StaticRoute::new().regenerate(move |_| subscribed.subscribe()))
                    view=move || {
                        let revision = page.revision.load(Ordering::SeqCst);
                        let response = expect_context::<ResponseOptions>();
                        response.append_header(header::HeaderName::from_static("x-isr-value"), header::HeaderValue::from_str(&format!("revision-{revision}")).unwrap());
                        response.append_header(header::HeaderName::from_static("x-isr-value"), header::HeaderValue::from_static("public"));
                        view! {
                            <h1>"Public ISR page"</h1>
                            <p>{format!("Revision {revision}, generated by process {}", std::process::id())}</p>
                            <p>"Live mode: POST /refresh, then reload this page."</p>
                        }
                    }
                />
            </Routes></Router>
        </body></html>
    }
}

async fn refresh(page: State<PublicPage>) -> HttpResponse {
    page.revision.fetch_add(1, Ordering::SeqCst);
    let mut updates = page.updates.lock().expect("page updates lock");
    match updates.as_mut().map(|sender| sender.try_send(())) {
        Some(Ok(())) => HttpResponse::Accepted().body("Refresh requested"),
        // Coalesce rapid changes: the next render reads the latest revision.
        // Keep one sender; request handlers do not clone channel reservations.
        Some(Err(error)) if error.is_full() => {
            HttpResponse::Accepted().body("Refresh already pending")
        }
        _ => HttpResponse::ServiceUnavailable().body("No live regeneration subscription"),
    }
}

fn main() -> std::io::Result<()> {
    ntex::rt::System::new(
        "leptos-ntex",
        leptos_ntex_unofficial::RequestRuntime::new(ntex::rt::DefaultRuntime),
    )
    .block_on(run())
}

async fn run() -> std::io::Result<()> {
    let mut site_root = None;
    let mut prebuilt = false;
    let mut bounded = false;
    for argument in std::env::args().skip(1) {
        if argument == "--prebuilt" {
            prebuilt = true;
        } else if argument == "--bounded" {
            bounded = true;
        } else if site_root.is_none() && !argument.starts_with('-') {
            site_root = Some(argument);
        } else {
            return Err(std::io::Error::new(
                std::io::ErrorKind::InvalidInput,
                "usage: isr_startup [site-root] [--prebuilt | --bounded]",
            ));
        }
    }
    if prebuilt && bounded {
        return Err(std::io::Error::new(
            std::io::ErrorKind::InvalidInput,
            "--bounded installs a writable policy; choose it or --prebuilt",
        ));
    }
    let options = LeptosOptions::builder()
        .output_name("isr_startup")
        .site_root(site_root.unwrap_or_else(|| "target/isr-site".to_string()))
        .build();
    let page = PublicPage::default();
    let app_fn = {
        let page = page.clone();
        move || shell(page.clone())
    };
    let (routes, generator) =
        generate_route_list_with_exclusions_and_ssg_and_context(app_fn.clone(), None, || {});
    let generator = if bounded {
        let policy = StaticRoutePolicy::open(
            &*options.site_root,
            StaticStorageLimits::new()
                .with_logical_file_bytes(1024 * 1024)
                .with_namespace_entries(64),
            StaticWorkLimits::new()
                .with_renders(2)
                .with_subscriptions(1)
                .with_waiters(16),
        )
        .await
        .map_err(std::io::Error::other)?;
        policy
            .configure_routes(&routes)
            .map_err(std::io::Error::other)?;
        generator
            .with_static_policy(policy)
            .map_err(std::io::Error::other)?
    } else {
        generator
    };
    if prebuilt {
        drop(generator);
    } else {
        // Run on the serving process's ntex runtime on every startup. Persisted
        // HTML and metadata do not contain this process's callback or Owner.
        generator
            .try_generate(&options)
            .await
            .map_err(std::io::Error::other)?;
    }
    web::server(move || {
        let options = options.clone();
        let routes = routes.clone();
        let app_fn = app_fn.clone();
        let page = page.clone();
        async move {
            let mut app = App::new().state(options).state(page);
            if !prebuilt {
                app = app.route("/refresh", web::post().to(refresh));
            }
            app.configure(move |cfg| register_leptos_routes(cfg, routes.clone(), app_fn.clone()))
        }
    })
    .bind(("127.0.0.1", 3000))?
    .run()
    .await
}
