#!/usr/bin/env bash
# Development environment setup script
# Called automatically by nix develop shellHook

export PATH="$HOME/.cargo/bin:$(pwd)/scripts:$PATH"

ra_info="$(which rust-analyzer):$(rust-analyzer --version 2>/dev/null || echo 'unknown')"
nixd_info="$(which nixd):$(nixd --version 2>/dev/null || echo 'unknown')"
current_hash=$(echo "$ra_info:$nixd_info" | sha256sum | cut -d' ' -f1)
stored_hash=""
if [ -f .zed/.lsp-hash ]; then
  stored_hash=$(cat .zed/.lsp-hash)
fi

if [ ! -f .zed/settings.json ] || [ "$current_hash" != "$stored_hash" ]; then
  echo "Generating .zed/settings.json..."
  mkdir -p .zed
  cat > .zed/settings.json << EOF
{
  "lsp": {
    "rust-analyzer": {
      "binary": {
        "path": "$(which rust-analyzer)"
      }
    },
    "nixd": {
      "binary": {
        "path": "$(which nixd)"
      }
    },
    "nil": {
      "binary": {
        "path": "$(which nixd)"
      }
    }
  },
  "languages": {
    "TOML": {
      "language_servers": ["taplo", "!package-version-server"]
    }
  },
  "context_servers": {
    "serena-context-server": {
      "settings": {
        "python_executable": "$(pwd)/.venv/bin/python"
      }
    }
  }
}
EOF
  echo "$current_hash" > .zed/.lsp-hash
fi

if [ ! -f .venv/bin/serena ]; then
  echo "Installing Serena in local venv..."
  uv venv --clear --python "$(which python3)" .venv
  uv pip install --python .venv/bin/python --quiet git+https://github.com/oraios/serena
  uv pip install --python .venv/bin/python --quiet serena-agent
fi

if [ ! -f .mcp.json ] || [ "$current_hash" != "$stored_hash" ]; then
  echo "Generating scripts/serena-mcp wrapper..."
  RA_DIR="$(which rust-analyzer | xargs dirname)"
  COREUTILS_DIR="$(which cat | xargs dirname)"
  BASH_DIR="$(which bash | xargs dirname)"
  cat > scripts/serena-mcp << WRAPPER
#!/usr/bin/env bash
# Wrapper script for Serena MCP server (auto-generated by dev-setup.sh)
# Sets up PATH correctly for NixOS before starting Serena

SCRIPT_DIR="\$(cd "\$(dirname "\$0")" && pwd)"
PROJECT_DIR="\$(dirname "\$SCRIPT_DIR")"

export PATH="\$SCRIPT_DIR:$RA_DIR:$COREUTILS_DIR:$BASH_DIR:\$HOME/.cargo/bin:\$PATH"

exec "\$PROJECT_DIR/.venv/bin/serena" "\$@"
WRAPPER
  chmod +x scripts/serena-mcp

  echo "Generating .mcp.json..."
  cat > .mcp.json << EOF
{
  "mcpServers": {
    "serena": {
      "command": "$(pwd)/scripts/serena-mcp",
      "args": [
        "start-mcp-server",
        "--context", "claude-code",
        "--project", "."
      ]
    },
    "context7": {
      "command": "$(pwd)/scripts/context7-mcp",
      "args": []
    },
    "github": {
      "command": "$(pwd)/scripts/github-mcp",
      "args": []
    }
  }
}
EOF
fi

SERENA_GLOBAL_CONFIG="$HOME/.serena/serena_config.yml"
if [ -f "$SERENA_GLOBAL_CONFIG" ]; then
  RA_PATH="$(which rust-analyzer)"
  CURRENT_RA=$(grep -A2 "ls_specific_settings:" "$SERENA_GLOBAL_CONFIG" | grep "path:" | sed 's/.*path: *"\?\([^"]*\)"\?.*/\1/' 2>/dev/null)
  if [ "$CURRENT_RA" != "$RA_PATH" ]; then
    echo "Updating ~/.serena/serena_config.yml with rust-analyzer path..."
    .venv/bin/python << PYEOF
import yaml
with open("$SERENA_GLOBAL_CONFIG", "r") as f:
    config = yaml.safe_load(f)
config["ls_specific_settings"] = {
    "rust": {
        "server": {
            "path": "$RA_PATH"
        }
    }
}
with open("$SERENA_GLOBAL_CONFIG", "w") as f:
    yaml.dump(config, f, default_flow_style=False, sort_keys=False)
PYEOF
  fi
fi
