//! The [`LeptosRoutes`] trait and its two implementations for ntex's
//! [`App`] and [`&mut ServiceConfig`], plus the [`register_leptos_routes`]
//! convenience wrapper.

use leptos::{IntoView, context::provide_context};
use leptos_router::SsrMode;
use ntex::web::error::StateExtractorError;
use ntex::web::{App, ErrorRenderer, ServiceConfig};
use std::collections::HashSet;

use crate::render::{
    render_app_async_with_context, render_app_to_stream_in_order_with_context,
    render_app_to_stream_with_context, render_app_to_stream_with_context_and_replace_blocks,
};
use crate::routes::NtexRouteListing;
use crate::server_fn::handlers::handle_specific_server_fn_with_context;
use crate::server_fn::registry::{lookup_server_fn, server_fn_paths};
use crate::static_routes::handle_static_route;

/// Adds a list of [`NtexRouteListing`]s and a Leptos app to an ntex router,
/// avoiding the need to use wildcards or to define every route manually.
pub trait LeptosRoutes {
    /// Registers routes that have been either
    /// 1. generated by `leptos_router`, or
    /// 2. emitted to handle a server function.
    fn leptos_routes<IV>(
        self,
        paths: Vec<NtexRouteListing>,
        app_fn: impl Fn() -> IV + Clone + Send + 'static,
    ) -> Self
    where
        IV: IntoView + 'static;

    /// Like [`LeptosRoutes::leptos_routes`], but runs `additional_context`
    /// for every request so you can inject more data into the reactive
    /// context.
    fn leptos_routes_with_context<IV>(
        self,
        paths: Vec<NtexRouteListing>,
        additional_context: impl Fn() + 'static + Clone + Send,
        app_fn: impl Fn() -> IV + Clone + Send + 'static,
    ) -> Self
    where
        IV: IntoView + 'static;
}

impl<M, T, Err> LeptosRoutes for App<M, T, Err>
where
    T: ntex::service::ServiceFactory<
            ntex::web::WebRequest<Err>,
            ntex::service::cfg::SharedCfg,
            Response = ntex::web::WebRequest<Err>,
            Error = Err::Container,
            InitError = (),
        >,
    Err: ErrorRenderer,
    Err::Container: From<StateExtractorError>,
{
    fn leptos_routes<IV>(
        self,
        paths: Vec<NtexRouteListing>,
        app_fn: impl Fn() -> IV + Clone + Send + 'static,
    ) -> Self
    where
        IV: IntoView + 'static,
    {
        self.leptos_routes_with_context(paths, || {}, app_fn)
    }

    fn leptos_routes_with_context<IV>(
        mut self,
        paths: Vec<NtexRouteListing>,
        additional_context: impl Fn() + 'static + Clone + Send,
        app_fn: impl Fn() -> IV + Clone + Send + 'static,
    ) -> Self
    where
        IV: IntoView + 'static,
    {
        let excluded = paths
            .iter()
            .filter(|p| p.exclude)
            .map(|p| p.path.as_str())
            .collect::<HashSet<_>>();

        for (path, method) in server_fn_paths() {
            if !excluded.contains(path)
                && let Some(server_fn) = lookup_server_fn(path, &method)
            {
                let additional_context = additional_context.clone();
                self = self.route(
                    path,
                    handle_specific_server_fn_with_context(server_fn, additional_context),
                );
            }
        }

        for listing in paths.iter().filter(|p| !p.exclude) {
            let path = listing.path();
            let mode = listing.mode();
            let is_static = matches!(mode, SsrMode::Static(_));

            // HEAD is routed through the GET handlers (`handle_static_route`
            // and `handle_response`), both of which register themselves for
            // GET + HEAD. ntex's h1 writer then strips the body at the
            // wire, giving RFC 9110 §9.3.2-compliant headers/status with
            // no body. Listings that only register POST/PUT/etc. will
            // correctly 405 on HEAD instead of returning a bogus 200.

            for method in listing.methods() {
                let additional_context = additional_context.clone();
                let additional_context_and_method = move || {
                    provide_context(method);
                    additional_context();
                };
                self = if is_static {
                    self.route(
                        path,
                        handle_static_route(
                            additional_context_and_method.clone(),
                            app_fn.clone(),
                            listing.regenerate.clone(),
                        ),
                    )
                } else {
                    self.route(
                        path,
                        match mode {
                            SsrMode::OutOfOrder => render_app_to_stream_with_context(
                                additional_context_and_method.clone(),
                                app_fn.clone(),
                                method,
                            ),
                            SsrMode::PartiallyBlocked => {
                                render_app_to_stream_with_context_and_replace_blocks(
                                    additional_context_and_method.clone(),
                                    app_fn.clone(),
                                    method,
                                    true,
                                )
                            }
                            SsrMode::InOrder => render_app_to_stream_in_order_with_context(
                                additional_context_and_method.clone(),
                                app_fn.clone(),
                                method,
                            ),
                            SsrMode::Async => render_app_async_with_context(
                                additional_context_and_method.clone(),
                                app_fn.clone(),
                                method,
                            ),
                            // `SsrMode` is `#[non_exhaustive]`; fall
                            // back to the out-of-order stream renderer
                            // for any future variant so we never panic
                            // at runtime if Leptos adds a new mode.
                            _ => {
                                #[cfg(feature = "tracing")]
                                tracing::warn!(
                                    "unknown SsrMode {:?}, falling back to OutOfOrder",
                                    mode
                                );
                                render_app_to_stream_with_context(
                                    additional_context_and_method.clone(),
                                    app_fn.clone(),
                                    method,
                                )
                            }
                        },
                    )
                };
            }
        }

        self
    }
}

impl<Err> LeptosRoutes for &mut ServiceConfig<Err>
where
    Err: ErrorRenderer,
    Err::Container: From<StateExtractorError>,
{
    fn leptos_routes<IV>(
        self,
        paths: Vec<NtexRouteListing>,
        app_fn: impl Fn() -> IV + Clone + Send + 'static,
    ) -> Self
    where
        IV: IntoView + 'static,
    {
        self.leptos_routes_with_context(paths, || {}, app_fn)
    }

    fn leptos_routes_with_context<IV>(
        self,
        paths: Vec<NtexRouteListing>,
        additional_context: impl Fn() + 'static + Clone + Send,
        app_fn: impl Fn() -> IV + Clone + Send + 'static,
    ) -> Self
    where
        IV: IntoView + 'static,
    {
        let mut router = self;

        let excluded = paths
            .iter()
            .filter(|p| p.exclude)
            .map(|p| p.path.as_str())
            .collect::<HashSet<_>>();

        for (path, method) in server_fn_paths() {
            if !excluded.contains(path)
                && let Some(server_fn) = lookup_server_fn(path, &method)
            {
                let additional_context = additional_context.clone();
                router = router.route(
                    path,
                    handle_specific_server_fn_with_context(server_fn, additional_context),
                );
            }
        }

        for listing in paths.iter().filter(|p| !p.exclude) {
            let path = listing.path();
            let mode = listing.mode();
            let is_static = matches!(mode, SsrMode::Static(_));

            // HEAD is handled by the GET route registrations below (see
            // the `App` impl for details).

            for method in listing.methods() {
                let additional_context = additional_context.clone();
                let additional_context_and_method = move || {
                    provide_context(method);
                    additional_context();
                };
                if is_static {
                    router = router.route(
                        path,
                        handle_static_route(
                            additional_context_and_method.clone(),
                            app_fn.clone(),
                            listing.regenerate.clone(),
                        ),
                    );
                } else {
                    router = router.route(
                        path,
                        match mode {
                            SsrMode::OutOfOrder => render_app_to_stream_with_context(
                                additional_context_and_method.clone(),
                                app_fn.clone(),
                                method,
                            ),
                            SsrMode::PartiallyBlocked => {
                                render_app_to_stream_with_context_and_replace_blocks(
                                    additional_context_and_method.clone(),
                                    app_fn.clone(),
                                    method,
                                    true,
                                )
                            }
                            SsrMode::InOrder => render_app_to_stream_in_order_with_context(
                                additional_context_and_method.clone(),
                                app_fn.clone(),
                                method,
                            ),
                            SsrMode::Async => render_app_async_with_context(
                                additional_context_and_method.clone(),
                                app_fn.clone(),
                                method,
                            ),
                            // `SsrMode` is `#[non_exhaustive]`; fall
                            // back to the out-of-order stream renderer
                            // for any future variant so we never panic
                            // at runtime if Leptos adds a new mode.
                            _ => {
                                #[cfg(feature = "tracing")]
                                tracing::warn!(
                                    "unknown SsrMode {:?}, falling back to OutOfOrder",
                                    mode
                                );
                                render_app_to_stream_with_context(
                                    additional_context_and_method.clone(),
                                    app_fn.clone(),
                                    method,
                                )
                            }
                        },
                    );
                }
            }
        }

        router
    }
}

/// Registers the Leptos route list on an ntex [`ServiceConfig`].
///
/// Convenience function that calls [`LeptosRoutes::leptos_routes`] on a
/// configuration object, for use from inside an [`App::configure`] closure.
pub fn register_leptos_routes<IV, Err>(
    cfg: &mut ServiceConfig<Err>,
    paths: Vec<NtexRouteListing>,
    app_fn: impl Fn() -> IV + Clone + Send + 'static,
) where
    Err: ErrorRenderer,
    Err::Container: From<StateExtractorError>,
    IV: IntoView + 'static,
{
    cfg.leptos_routes(paths, app_fn);
}
