name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: dtolnay/rust-toolchain@1.88
      with:
        components: rustfmt, clippy
    - name: Check formatting
      run: cargo fmt --all -- --check
    - name: Clippy
      run: cargo clippy --all-targets --all-features -- -D warnings
    - name: Test
      run: cargo test --all-features --verbose
    - name: Docs
      run: RUSTDOCFLAGS="-D warnings" cargo doc --all-features --no-deps
